# Generated by Django 4.0.5 on 2022-06-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafiki_app', '0002_category_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='uploads/'),
        ),
    ]
