# Generated by Django 4.0.5 on 2022-06-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafiki_app', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.BooleanField(null=True),
        ),
    ]
